name: Storybook Deployment
on:
Â Â pull_request:
Â Â Â Â branches:
Â Â Â Â Â Â - develop
jobs:
Â Â storybook:
Â Â Â Â runs-on: ubuntu-20.04
Â Â Â Â permissions: write-all
Â Â Â Â outputs:
Â Â Â Â Â Â status: ${{ job.status }}
Â Â Â Â steps:
Â Â Â Â Â Â - name: checkout repository
Â Â Â Â Â Â Â Â uses: actions/checkout@v3
Â Â Â Â Â Â Â Â with:
Â Â Â Â Â Â Â Â Â Â fetch-depth: 0

Â Â Â Â Â Â - name: cache dependencies
Â Â Â Â Â Â Â Â id: cache
Â Â Â Â Â Â Â Â uses: actions/cache@v3
Â Â Â Â Â Â Â Â with:
Â Â Â Â Â Â Â Â Â Â path: '**/node_modules'
Â Â Â Â Â Â Â Â Â Â key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-storybook

Â Â Â Â Â Â - name: depedency install
Â Â Â Â Â Â Â Â if: steps.cache.outputs.cache-hit != 'true'
Â Â Â Â Â Â Â Â run: npm ci

Â Â Â Â Â Â - name: publish to chromatic
Â Â Â Â Â Â Â Â id: chromatic
Â Â Â Â Â Â Â Â uses: chromaui/action@v1
Â Â Â Â Â Â Â Â with:
Â Â Â Â Â Â Â Â Â Â projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
Â Â Â Â Â Â Â Â Â Â token: ${{ secrets.GITHUB_TOKEN }}

Â Â Â Â Â Â - name: comment PR
Â Â Â Â Â Â Â Â uses: thollander/actions-comment-pull-request@v1
Â Â Â Â Â Â Â Â env:
Â Â Â Â Â Â Â Â Â Â GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Â Â Â Â Â Â Â Â with:
Â Â Â Â Â Â Â Â Â Â message: 'ðŸš€storybook: ${{ steps.chromatic.outputs.storybookUrl }}'
ì¶œì²˜: https://feb-dain.tistory.com/9 [FEB:)DAIN:í‹°ìŠ¤í† ë¦¬]
